/**
 * Client-side pagefind composable.
 *
 * Pagefind is a static search index generated at build time by running
 * `pnpm pagefind:build` after `nuxt build`. Its JS bundle lives at
 * /pagefind/pagefind.js in the compiled site.
 *
 * Result enrichment: pagefind returns URLs + excerpts. To avoid extra API
 * calls, each result is enriched with its full metadata (imageUrl, categories,
 * authors, date) by looking it up in the pre-built search-index.json loaded
 * here alongside the pagefind engine.
 */

import type { SearchItem } from './useSearch'

export interface FileParent {
  type: 'article' | 'dataset'
  slug: string
  title: string
  url: string
}

export interface PagefindResult {
  item: SearchItem | null
  url: string
  /** HTML string with <mark> tags for matched terms — safe to v-html. */
  excerpt: string
  type: 'article' | 'app' | 'dataset' | 'project' | 'file'
  slug: string
  /** For file results: the actual downloadable/viewable file URL. */
  fileUrl?: string
  /** Display name for file results. */
  fileName?: string
  /** Distinguishes indexed media types. */
  fileType?: 'pdf' | 'excel'
  /** For file results: the article(s)/dataset(s) this file belongs to. */
  parents?: FileParent[]
}

interface RawPagefindResult {
  url: string
  excerpt: string
  meta: Record<string, string>
  sub_results?: Array<{ title: string; url: string; excerpt: string }>
}

// Module-level singletons — client-only, never written during SSR.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let _pagefind: any = null
let _inflight: Promise<void> | null = null

// Constructed via `new Function` so neither Vite's dev import-analysis nor
// Rollup's prod bundler can see the URL as a static string. /pagefind/pagefind.js
// is generated by `pagefind:build` AFTER `nuxt build`, so it cannot exist at
// compile time. The browser does the real fetch when this runs at runtime.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const dynamicImport = new Function('url', 'return import(url)') as (url: string) => Promise<any>

export const usePagefind = () => {
  const isLoaded = useState<boolean>('pagefind:loaded', () => false)
  const isLoading = useState<boolean>('pagefind:loading', () => false)
  const loadError = useState<string | null>('pagefind:error', () => null)

  // Metadata items loaded from search-index.json — used only for enrichment.
  // Stored in a separate useState key so it doesn't conflict with useSearch.
  const metaItems = useState<SearchItem[]>('pagefind:meta', () => [])

  // hash → [parents] map from file-parents.json, used to surface the parent
  // article/dataset on file result cards.
  const fileParents = useState<Record<string, FileParent[]>>('pagefind:fileParents', () => ({}))

  const load = async (): Promise<void> => {
    if (!import.meta.client) return
    if (isLoaded.value) return
    if (_inflight) { await _inflight; return }

    isLoading.value = true
    loadError.value = null

    _inflight = (async () => {
      try {
        // Load in parallel: pagefind engine + metadata index + file→parent map
        const [pagefindModule, metaData, parentMap] = await Promise.all([
          dynamicImport('/pagefind/pagefind.js'),
          $fetch<SearchItem[]>('/search-index.json').catch(() => [] as SearchItem[]),
          $fetch<Record<string, FileParent[]>>('/file-parents.json').catch(() => ({} as Record<string, FileParent[]>))
        ])

        _pagefind = pagefindModule
        await _pagefind.init()
        metaItems.value = metaData
        fileParents.value = parentMap
        isLoaded.value = true
      } catch {
        loadError.value =
          'Search index not available. Run `pnpm build:full` (or `pnpm build && pnpm pagefind:build`) to generate it.'
      } finally {
        isLoading.value = false
        _inflight = null
      }
    })()

    await _inflight
  }

  /** Search via pagefind. Returns up to 60 results enriched with search-index.json metadata. */
  const search = async (query: string): Promise<PagefindResult[]> => {
    if (!query.trim() || !_pagefind) return []

    // Wrap in double quotes to force exact-phrase matching (no stemming/fuzzy).
    // Strip any user-supplied quotes first so the wrap stays well-formed.
    const phraseQuery = `"${query.replace(/"/g, '').trim()}"`
    const response = await _pagefind.search(phraseQuery)
    if (!response?.results?.length) return []

    const rawResults: RawPagefindResult[] = await Promise.all(
      response.results
        .slice(0, 60)
        .map((r: { data: () => Promise<RawPagefindResult> }) => r.data())
    )

    // Extract the Strapi file hash from a `/attachments/...` URL so we can
    // look the file up in the parent map. PDF stubs are `attachments/pdf/<hash>.html`;
    // Excel stubs are `attachments/excel/<hash>.html`.
    const hashFromUrl = (url: string): string => {
      const file = url.split('/').pop() ?? ''
      return file.replace(/\.(pdf|html)$/i, '')
    }

    return rawResults.map((raw) => {
      // ── File results: PDF stubs at /attachments/pdf/<hash>.html, Excel at /attachments/excel/<hash>.html ──
      if (/\/attachments\/pdf\//.test(raw.url)) {
        return {
          item: null,
          url: raw.url,
          excerpt: raw.excerpt,
          type: 'file',
          slug: '',
          fileType: 'pdf',
          fileUrl: raw.meta?.fileUrl ?? '',
          fileName: raw.meta?.title ?? '',
          parents: fileParents.value[hashFromUrl(raw.url)] ?? []
        }
      }

      if (/\/attachments\/excel\//.test(raw.url)) {
        return {
          item: null,
          url: raw.url,
          excerpt: raw.excerpt,
          type: 'file',
          slug: '',
          fileType: 'excel',
          fileUrl: raw.meta?.fileUrl ?? '',
          fileName: raw.meta?.title ?? '',
          parents: fileParents.value[hashFromUrl(raw.url)] ?? []
        }
      }

      // ── Content results: articles, apps, datasets ────────────────────────
      // Derive content type and slug from the URL path:
      //   /articles/my-slug  → type='article',  slug='my-slug'
      //   /apps/my-slug      → type='app',      slug='my-slug'
      //   /datasets/my-slug  → type='dataset',  slug='my-slug'
      const match = raw.url.match(/^\/(articles|apps|datasets)\/([^/?#]+)/)
      const urlSegment = match?.[1]
      const slug = match?.[2] ?? ''

      const typeMap: Record<string, PagefindResult['type']> = {
        articles: 'article',
        apps: 'app',
        datasets: 'dataset'
      }
      const type: PagefindResult['type'] = typeMap[urlSegment ?? ''] ?? 'article'

      const item = urlSegment
        ? (metaItems.value.find((i: SearchItem) => i.type === type && i.slug === slug) ?? null)
        : null

      return { item, url: raw.url, excerpt: raw.excerpt, type, slug }
    })
  }

  return { load, search, isLoaded, isLoading, loadError }
}
